#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/app/node_modules/.pnpm/msw@1.3.2_typescript@5.2.2/node_modules/msw/cli/node_modules:/app/node_modules/.pnpm/msw@1.3.2_typescript@5.2.2/node_modules/msw/node_modules:/app/node_modules/.pnpm/msw@1.3.2_typescript@5.2.2/node_modules:/app/node_modules/.pnpm/node_modules"
else
  export NODE_PATH="/app/node_modules/.pnpm/msw@1.3.2_typescript@5.2.2/node_modules/msw/cli/node_modules:/app/node_modules/.pnpm/msw@1.3.2_typescript@5.2.2/node_modules/msw/node_modules:/app/node_modules/.pnpm/msw@1.3.2_typescript@5.2.2/node_modules:/app/node_modules/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../cli/index.js" "$@"
else
  exec node  "$basedir/../../cli/index.js" "$@"
fi
